[package]
name = "geodo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
csv = "1.2.2"
dialoguer = "0.10.4"
serde = { version = "1.0.171", features = ["derive"] }
